### ISSUE TITLE
Not working on WPF project

### ISSUE THREAD

**Issue by ghost** [jamesseanwright/simple-http#1]
Thanks for excellent works.

I can run it with console application but I can not run with wpf application.

In the output window, it seems to normal, but there is no response at server.  
Initialising server on port 8005...
Listening for requests on port 8005.

There is no error messages and I can not figure out what is wrong in it.

**Comment by jamesseanwright** [comment]
Hey!

Thanks for your interest in Simple HTTP! I admittedly haven't worked on this project in a while, but I'm happy to investigate.

Do you have a repo or a code example to share that demonstrates how you are using the library?

Also, have you tried running it with the debugger attached to see if your solution throws any runtime exceptions?

Cheers,
James

**Comment by ghost** [comment]
Thanks for response.

I was looking for simple-http server. For small size project, node.js or asp.net has a burden to install and configure.

JamesWright.SimpleHttp project is very impressive. It is simple and concise and well structured. 
Further it supports simple REST routing API. 

I have created simple c# winform and wpf applicaion and put your sample code to loaded events. 

// from winform applicaon
        private void Form1_Load_1(object sender, System.EventArgs e)
        {
            App app = new App();
            app.Get("/", async (req, res) =>
            {
                res.Content = "<p>You did a GET.</p>";
                res.ContentType = "text/html";
                await res.SendAsync();
            });
            app.Start();
        }

I found server is running but the server not responding to the http://localhost:8005 request. There's no runtime exceptions.

# 

# Test Results
1. With Console application
   C:>netstat -aon | findstr :8005
   TCP    0.0.0.0:8005           0.0.0.0:0              LISTENING       4
   TCP    [::]:8005              [::]:0                 LISTENING       4

// Results : OK
C:>curl http://localhost:8005

<p>You did a GET.</p>
1. With winform or wpf application
   C:>netstat -aon | findstr :8005
   TCP    0.0.0.0:8005           0.0.0.0:0              LISTENING       4
   TCP    [::]:8005              [::]:0                 LISTENING       4
   TCP    [::1]:6678             [::1]:8005             TIME_WAIT       0

// Results: No response, Pending.
C:>curl http://localhost:8005

There is TIME_WAIT in winform or wpf test. 
I think the TIME_WAIT makes problems, but I don't know about it.

I have limited knowledge about network technology, I don't know what is problems. 

Thanks.

**Comment by jamesseanwright** [comment]
Hmm, that should work at first glimpse. I'll try to create sample WinForms and WPF projects over the next few days to see if I can reproduce the issue. Thanks again for bringing this to my attention 😄
